apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudshiftg-secrets
  namespace: development
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: cloudshiftg-secrets
    creationPolicy: Owner
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: cloudshiftg-session-secret
    - secretKey: DATABASE_URL
      remoteRef:
        key: cloudshiftg-database-url
    - secretKey: APP_DATABASE_URL
      remoteRef:
        key: cloudshiftg-app-database-url
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: cloudshiftg-aws-access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: cloudshiftg-aws-secret-access-key
    - secretKey: AWS_REGION
      remoteRef:
        key: cloudshiftg-aws-region
    - secretKey: GCP_BILLING_API_KEY
      remoteRef:
        key: cloudshiftg-gcp-billing-api-key
