{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.fullname }}
  annotations:
    {{- if .Values.ingress.managedCertificate }}
    networking.gke.io/managed-certificates: {{ .Values.fullname }}-cert
    {{- end }}
    kubernetes.ingress.kubernetes.io/redirect-to-https: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.fullname }}-web
                port:
                  number: 80
{{- end }}
