{{- if and .Values.ingress.enabled .Values.ingress.managedCertificate }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.fullname }}-cert
spec:
  domains:
    - {{ .Values.ingress.host }}
{{- end }}
