{{- if .Values.serviceAccount.web.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.web.name }}
  labels:
    app.kubernetes.io/name: cloudshiftg
    app.kubernetes.io/component: web
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.web.gcpServiceAccount | quote }}
{{- end }}
---
{{- if .Values.serviceAccount.worker.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.worker.name }}
  labels:
    app.kubernetes.io/name: cloudshiftg
    app.kubernetes.io/component: worker
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.worker.gcpServiceAccount | quote }}
{{- end }}
---
{{- if .Values.serviceAccount.terraformJob.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.terraformJob.name }}
  labels:
    app.kubernetes.io/name: cloudshiftg
    app.kubernetes.io/component: terraform-job
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.terraformJob.gcpServiceAccount | quote }}
{{- end }}
