environment: development

cloudsql:
  enabled: true

migrate:
  # Safe with hook-failed delete policy on the migrate Job template.
  enabled: true

web:
  replicas: 1
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 4

worker:
  replicas: 1
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 4

ingress:
  enabled: false
  host: cloudshiftg-dev.example.com

secrets:
  awsOptional: false
