apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudshiftg-eso-sa
  namespace: staging
  annotations:
    iam.gke.io/gcp-service-account: cloudshiftg-eso@project-7fe2c753-1df6-4821-bf9.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: staging
spec:
  provider:
    gcpsm:
      projectID: project-7fe2c753-1df6-4821-bf9
      auth:
        workloadIdentity:
          clusterLocation: us-east1
          clusterName: cloudshiftg-autopilot-dev
          serviceAccountRef:
            name: cloudshiftg-eso-sa
